### ISSUE TITLE
SEO Enhancement

### ISSUE THREAD

**Issue by gkatrakazas** [wwWallet/wallet-frontend#164]
We need to improve the SEO of our wwWallet. This involves updating the index.html with appropriate meta tags, creating a robots.txt and sitemap.xml in the public director. The goal is to enhance search engine visibility and ranking.

**Comment by nvoutsin** [comment]
[W3C Web Application Manifest Spec](https://w3c.github.io/manifest/) would also be useful to prepare the PWA version of wwWallet

**Comment by gkatrakazas** [comment]
I agree that this is an important enhancement. To keep our work organized, I have opened a separate issue #165.
