### ISSUE TITLE
Standardization and Accessibility Improvement of Button Components

### ISSUE THREAD

**Issue by gkatrakazas** [wwWallet/wallet-frontend#220]
### Description
We've identified the need to organize all types of buttons in our application into a standardized set of components. This effort includes unifying the styling, particularly focus styles, and ensuring all buttons are accessible, especially via keyboard navigation (Tab key), display title on hover etc.

### Objectives
1. **Component Organization**: Create a well-defined set of button components. This could include primary buttons, cancel buttons, etc.
2. **Consistent Styling**: Ensure consistent styling across all button types. This includes colors, hover states, and sizes.
3. **Focus Style Uniformity**: Implement a consistent and noticeable focus style across all button components to improve usability and accessibility.
4. **Keyboard Accessibility**: Ensure all buttons are accessible using the Tab key. This includes making sure that buttons can gain focus and that the focus order is logical and intuitive.

### Expected Outcomes
- A cohesive set of button components that can be reused throughout the application.
- Improved user experience through consistent and appealing button designs.
- Enhanced accessibility, particularly for keyboard and screen reader users.

**Comment by emlun** [comment]
Recommended reading:
- [Using the tabindex attribute](https://www.tpgi.com/using-the-tabindex-attribute/)
- [The `autofocus` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus)

Note this concern in particular:
>Use careful consideration for accessibility when applying the `autofocus` attribute. Automatically focusing on a control can cause the page to scroll on load. The focus can also cause dynamic keyboards to display on some touch devices. While a screen reader will announce the label of the form control receiving focus, the screen reader will not announce anything before the label, and the sighted user on a small device will equally miss the context created by the preceding content.

For example: while I would love to autofocus the "Continue" button in the "Almost done!" dialogs during WebAuthn credential registration, I'm not sure if that would cause accessibility issues like that described above. In that case, would screen readers not read the explanatory text preceding the buttons? I don't know.

I certainly do support the "Keyboard Accessibility" objective, just wanted to share some of my own uncertainties around possible pitfalls.

**Comment by gkatrakazas** [comment]
You're absolutely right about being careful with features like `autofocus` and `tabindex`. We need to make sure we don't disrupt the user experience on different devices. 

As for `autofocus`, I am really sure if we going ot use it. Instead, we’ll focus on making our `focus` style clear and visible. This is the style that shows up when someone clicks on an element or selects it with the Tab key. Our main goal is to make sure our users can navigate easily using just their keyboard. This way, they’ll always know which button or input they're on. And, of course, we'll test everything thoroughly to make sure it all works smoothly.
